### ISSUE TITLE
index.html not displaying on github-pages

### ISSUE THREAD

**Issue by scordle** [asams1859/CSC_230_Website_Design_2021#103]
Be sure that your index.html page is named only 'index.html'.  It's a web server thing.  If you remove that, everything should work.

**Comment by scordle** [comment]
Resolved.  The new page works when you view the deployment.

**Comment by asams1859** [comment]
Oh my goodness!!! Thank you so much for finding and fixing my error!

Ssndra

On May 13, 2021 7:55 PM, Scott Cordle ***@***.***> wrote:

Warning: This message is from outside the organization. Beware when clicking any links and opening any attachments.

Be sure that your index.html page is named only 'index.html'. It's a web server thing. If you remove that, everything should work.
